title: Firdhila Ananda Syahputri
email: firdhilaas@gmail.com
description: Nama saya Firdhila Ananda Syahputri, biasanya dipanggil Firdhila.Saya lahir di Lhokseumawe pada 18 Mei 2006. Saya merupakan mahasiswa semester 2 jurusan Teknologi Informasi dan Komputer prodi Teknik Informatika di Politeknik Negeri Lhokseumawe.<br> 
        
url : 'https://firdhilaananda.github.io'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag